recipe_sha: c854662981a3d7558f8d46dbe799bbbe9826d232fe213bd223ebebee316ec570  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  Packaged license file/s.
  INFO :: Time taken to mark (prefix)
          0 replacements in 0 files was 0.02 seconds
  WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
  TEST START: /opt/conda/conda-bld/linux-64/python-libsbml-5.18.0-py310hb4f6fe0_7.tar.bz2
  Renaming work directory '/opt/conda/conda-bld/python-libsbml_1717631421467/work' to '/opt/conda/conda-bld/python-libsbml_1717631421467/work_moved_python-libsbml-5.18.0-py310hb4f6fe0_7_linux-64'
  shutil.move(work)=/opt/conda/conda-bld/python-libsbml_1717631421467/work, dest=/opt/conda/conda-bld/python-libsbml_1717631421467/work_moved_python-libsbml-5.18.0-py310hb4f6fe0_7_linux-64)
  Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/python-libsbml_1717631421467/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:    0.1-conda_forge            conda-forge
      _openmp_mutex:    4.5-2_gnu                  conda-forge
      bzip2:            1.0.8-hd590300_5           conda-forge
      ca-certificates:  2024.6.2-hbcca054_0        conda-forge
      icu:              73.2-h59595ed_0            conda-forge
      ld_impl_linux-64: 2.40-hf3520f5_2            conda-forge
      libffi:           3.4.2-h7f98852_5           conda-forge
      libgcc-ng:        13.2.0-h77fa898_7          conda-forge
      libgomp:          13.2.0-h77fa898_7          conda-forge
      libiconv:         1.17-hd590300_2            conda-forge
      libnsl:           2.0.1-hd590300_0           conda-forge
      libsqlite:        3.45.3-h2797004_0          conda-forge
      libstdcxx-ng:     13.2.0-hc0a3c3a_7          conda-forge
      libuuid:          2.38.1-h0b41bf4_0          conda-forge
      libxcrypt:        4.4.36-hd590300_1          conda-forge
      libxml2:          2.12.7-hc051c1a_1          conda-forge
      libzlib:          1.3.1-h4ab18f5_1           conda-forge
      ncurses:          6.5-h59595ed_0             conda-forge
      openssl:          3.3.1-h4ab18f5_0           conda-forge
      pip:              24.0-pyhd8ed1ab_0          conda-forge
      python:           3.10.14-hd12c33a_0_cpython conda-forge
      python-libsbml:   5.18.0-py310hb4f6fe0_7     local
      python_abi:       3.10-4_cp310               conda-forge
      readline:         8.2-h8228510_1             conda-forge
      setuptools:       70.0.0-pyhd8ed1ab_0        conda-forge
      tk:               8.6.13-noxft_h4845f30_101  conda-forge
      tzdata:           2024a-h0c530f3_0           conda-forge
      wheel:            0.43.0-pyhd8ed1ab_1        conda-forge
      xz:               5.2.6-h166bdaf_0           conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  export PREFIX=/opt/conda/conda-bld/python-libsbml_1717631421467/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
  export SRC_DIR=/opt/conda/conda-bld/python-libsbml_1717631421467/test_tmp
  import: 'libsbml'
  import: 'libsbml'

  Resource usage statistics from testing python-libsbml:
     Process count: 2
     CPU time: Sys=0:00:00.0, User=-
     Memory: 11.1M
     Disk usage: 16B
     Time elapsed: 0:00:02.0


  TEST END: /opt/conda/conda-bld/linux-64/python-libsbml-5.18.0-py310hb4f6fe0_7.tar.bz2
  Renaming work directory '/opt/conda/conda-bld/python-libsbml_1717631421467/work' to '/opt/conda/conda-bld/python-libsbml_1717631421467/work_moved_python-libsbml-5.18.0-py310hb4f6fe0_7_linux-64_main_build_loop'
  shutil.move(work)=/opt/conda/conda-bld/python-libsbml_1717631421467/work, dest=/opt/conda/conda-bld/python-libsbml_1717631421467/work_moved_python-libsbml-5.18.0-py310hb4f6fe0_7_linux-64_main_build_loop)
  Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2308, in build
      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 916, in expand_outputs
      for output_dict, m in deepcopy(_m).get_output_metadata_set(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 2737, in get_output_metadata_set
      conda_packages = finalize_outputs_pass(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 1095, in finalize_outputs_pass
      fm = finalize_metadata(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 650, in finalize_metadata
      build_unsat, host_unsat = add_upstream_pins(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 491, in add_upstream_pins
      host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 453, in _read_upstream_pin_files
      extra_run_specs = get_upstream_pins(m, precs, env)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 425, in get_upstream_pins
      loc, dist = execute_download_actions(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 392, in execute_download_actions
      pfe.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Error with archive /opt/conda/pkgs/python-3.12.3-hab00c5b_0_cpython.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
# Last 100 lines of the build log.
