recipe_sha: dd10a771d8320104a3a7f0740c3d9bb23d2d56632a7d8937b088b823ced56e11  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
      xyzservices:             2024.6.0-pyhd8ed1ab_0         conda-forge
      xz:                      5.2.6-h166bdaf_0              conda-forge
      yaml:                    0.2.5-h7f98852_2              conda-forge
      zict:                    3.0.0-pyhd8ed1ab_0            conda-forge
      zipp:                    3.18.1-pyhd8ed1ab_0           conda-forge
      zlib-ng:                 2.0.7-h0b41bf4_0              conda-forge
      zstd:                    1.5.6-ha6fb4c9_0              conda-forge

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3653, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3397, in test
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1332, in _execute_actions
      progressive_fetch_extract.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Error with archive /opt/conda/pkgs/scipy-1.10.1-py38h59b608b_3.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/scikit-learn-1.3.2-py38ha25d942_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device: '/opt/conda/pkgs/scikit-learn-1.3.2-py38ha25d942_2/lib/python3.8/site-packages/sklearn/linear_model/_glm/tests/__pycache__'
  Error with archive /opt/conda/pkgs/pandas-2.0.3-py38h01efb38_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/bokeh-3.1.1-pyhd8ed1ab_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/numpy-1.24.4-py38h59b608b_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pyarrow-core-16.1.0-py38he753e70_1_cpu.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pytables-3.8.0-py38h606e206_4.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/fonttools-4.53.0-py38hfb59056_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pysam-0.22.1-py38h2d19e03_1.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/numba-0.58.1-py38h4144172_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/h5py-3.11.0-nompi_py38h55b5aab_102.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/biopython-1.83-py38h01eb140_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/multiprocess-0.70.16-py38h01eb140_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pyyaml-6.0.1-py38h01eb140_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/cooltools-0.3.2-py38hf6cf242_4.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/kiwisolver-1.4.5-py38h7f3f72f_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pooch-1.8.2-pyhd8ed1ab_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/simplejson-3.19.2-py38h01eb140_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/partd-1.4.1-pyhd8ed1ab_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pyarrow-16.1.0-py38hb563948_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device: '/opt/conda/pkgs/pyarrow-16.1.0-py38hb563948_1/info/test'
  Error with archive /opt/conda/pkgs/pairix-0.3.8-py38h6bfa29d_2.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/liblapack-3.9.0-20_linux64_openblas.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device: '/opt/conda/pkgs/liblapack-3.9.0-20_linux64_openblas/info/recipe'
  Error with archive /opt/conda/pkgs/libcblas-3.9.0-20_linux64_openblas.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/libblas-3.9.0-20_linux64_openblas.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/pillow-10.3.0-py38h9e66945_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
# Last 100 lines of the build log.
