recipe_sha: c8fdd7d1be49e7c2e5e03c78e8ef8e5da084a2de40931b17429baec27d330480  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
     Time elapsed: 0:00:14.0


  Packaging emu-pca
  Packaging emu-pca-1.0-py311h1abe8b6_1
  compiling .pyc files...
  number of files: 22
  Warning: rpath /opt/conda/conda-bld/emu-pca_1717557690386/_build_env/lib is outside prefix /opt/conda/conda-bld/emu-pca_1717557690386/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place (removing it)
  Warning: rpath /opt/conda/conda-bld/emu-pca_1717557690386/_build_env/lib is outside prefix /opt/conda/conda-bld/emu-pca_1717557690386/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place (removing it)
     INFO: sysroot: '/opt/conda/conda-bld/emu-pca_1717557690386/_build_env/x86_64-conda-linux-gnu/sysroot/' files: '['usr/share/zoneinfo/zone.tab', 'usr/share/zoneinfo/tzdata.zi', 'usr/share/zoneinfo/right/Zulu', 'usr/share/zoneinfo/right/WET']'
  WARNING (emu-pca,lib/python3.11/site-packages/src/shared_cy.cpython-311-x86_64-linux-gnu.so): Needed DSO lib/libgomp.so.1 found in ['conda-forge/linux-64::_openmp_mutex==4.5=2_gnu']
  WARNING (emu-pca,lib/python3.11/site-packages/src/shared_cy.cpython-311-x86_64-linux-gnu.so): .. but ['conda-forge/linux-64::_openmp_mutex==4.5=2_gnu'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
     INFO (emu-pca,lib/python3.11/site-packages/src/shared_cy.cpython-311-x86_64-linux-gnu.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.12=he073ed8_17
  WARNING (emu-pca,lib/python3.11/site-packages/src/memory_cy.cpython-311-x86_64-linux-gnu.so): Needed DSO lib/libgomp.so.1 found in ['conda-forge/linux-64::_openmp_mutex==4.5=2_gnu']
  WARNING (emu-pca,lib/python3.11/site-packages/src/memory_cy.cpython-311-x86_64-linux-gnu.so): .. but ['conda-forge/linux-64::_openmp_mutex==4.5=2_gnu'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
     INFO (emu-pca,lib/python3.11/site-packages/src/memory_cy.cpython-311-x86_64-linux-gnu.so): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.12=he073ed8_17
  WARNING (emu-pca): interpreter (Python) package conda-forge/linux-64::python==3.11.9=hb806964_0_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to build/ignore_run_exports)
  WARNING (emu-pca): run-exports library package conda-forge/linux-64::numpy==1.23.5=py311h7d28db0_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to build/ignore_run_exports)
  Fixing permissions
  Packaged license file/s.
  INFO :: Time taken to mark (prefix)
          0 replacements in 0 files was 0.01 seconds
  Files containing CONDA_PREFIX
  -----------------------------
  bin/emu (text): Patching
  WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
  TEST START: /opt/conda/conda-bld/linux-64/emu-pca-1.0-py311h1abe8b6_1.tar.bz2
  Renaming work directory '/opt/conda/conda-bld/emu-pca_1717557690386/work' to '/opt/conda/conda-bld/emu-pca_1717557690386/work_moved_emu-pca-1.0-py311h1abe8b6_1_linux-64'
  shutil.move(work)=/opt/conda/conda-bld/emu-pca_1717557690386/work, dest=/opt/conda/conda-bld/emu-pca_1717557690386/work_moved_emu-pca-1.0-py311h1abe8b6_1_linux-64)
  Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/emu-pca_1717557690386/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:    0.1-conda_forge            conda-forge
      _openmp_mutex:    4.5-2_gnu                  conda-forge
      bzip2:            1.0.8-hd590300_5           conda-forge
      ca-certificates:  2024.6.2-hbcca054_0        conda-forge
      emu-pca:          1.0-py311h1abe8b6_1        local
      ld_impl_linux-64: 2.40-hf3520f5_2            conda-forge
      libblas:          3.9.0-22_linux64_openblas  conda-forge
      libcblas:         3.9.0-22_linux64_openblas  conda-forge
      libexpat:         2.6.2-h59595ed_0           conda-forge
      libffi:           3.4.2-h7f98852_5           conda-forge
      libgcc-ng:        13.2.0-h77fa898_7          conda-forge
      libgfortran-ng:   13.2.0-h69a702a_7          conda-forge
      libgfortran5:     13.2.0-hca663fb_7          conda-forge
      libgomp:          13.2.0-h77fa898_7          conda-forge
      liblapack:        3.9.0-22_linux64_openblas  conda-forge
      libnsl:           2.0.1-hd590300_0           conda-forge
      libopenblas:      0.3.27-pthreads_h413a1c8_0 conda-forge
      libsqlite:        3.45.3-h2797004_0          conda-forge
      libstdcxx-ng:     13.2.0-hc0a3c3a_7          conda-forge
      libuuid:          2.38.1-h0b41bf4_0          conda-forge
      libxcrypt:        4.4.36-hd590300_1          conda-forge
      libzlib:          1.3.1-h4ab18f5_1           conda-forge
      ncurses:          6.5-h59595ed_0             conda-forge
      numpy:            1.26.4-py311h64a7726_0     conda-forge
      openssl:          3.3.1-h4ab18f5_0           conda-forge
      pip:              24.0-pyhd8ed1ab_0          conda-forge
      python:           3.11.9-hb806964_0_cpython  conda-forge
      python_abi:       3.11-4_cp311               conda-forge
      readline:         8.2-h8228510_1             conda-forge
      setuptools:       70.0.0-pyhd8ed1ab_0        conda-forge
      tk:               8.6.13-noxft_h4845f30_101  conda-forge
      tzdata:           2024a-h0c530f3_0           conda-forge
      wheel:            0.43.0-pyhd8ed1ab_1        conda-forge
      xz:               5.2.6-h166bdaf_0           conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  ERROR conda.core.link:_execute(950): An error occurred while installing package 'conda-forge::numpy-1.26.4-py311h64a7726_0'.
  Rolling back transaction: ...working... done
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3653, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3397, in test
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1334, in _execute_actions
      unlink_link_transaction.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 354, in execute
      self._execute(
    File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 970, in _execute
      raise CondaMultiError(
  conda.CondaMultiError: [Errno 28] No space left on device: '/opt/conda/conda-bld/emu-pca_1717557690386/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/site-packages/numpy/f2py/tests/src'
  ()
# Last 100 lines of the build log.
