recipe_sha: 4d9e5001e22e5b78ca0209858d77c1459d71c7e695f048d6d8dffa429ac60398  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  -CMAKE_PREFIX_PATH=$PREFIX:$PREFIX/x86_64-conda-linux-gnu/sysroot/usr
  -CONDA_BUILD_SYSROOT=$PREFIX/x86_64-conda-linux-gnu/sysroot
  -CPP=$PREFIX/bin/x86_64-conda-linux-gnu-cpp
  -CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
  -DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rpbp-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  -DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
  -GCC=$PREFIX/bin/x86_64-conda-linux-gnu-gcc
  -GCC_AR=$PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
  -GCC_NM=$PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
  -GCC_RANLIB=$PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
  -LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
  INFO: activate-gxx_linux-64.sh made the following environmental changes:
  CXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
  CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rpbp-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rpbp-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
  DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rpbp-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rpbp-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
  -CXX=$PREFIX/bin/x86_64-conda-linux-gnu-c
  -CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rpbp-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  -CXX_FOR_BUILD=$PREFIX/bin/x86_64-conda-linux-gnu-c
  -DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rpbp-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  -GXX=$PREFIX/bin/x86_64-conda-linux-gnu-g
  Using pip 24.0 from $PREFIX/lib/python3.11/site-packages/pip (python 3.11)
  Non-user install because user site-packages disabled
  Ignoring indexes: https://pypi.org/simple
  Created temporary directory: /tmp/pip-build-tracker-m7ak8htb
  Initialized build tracking at /tmp/pip-build-tracker-m7ak8htb
  Created build tracker: /tmp/pip-build-tracker-m7ak8htb
  Entered build tracker: /tmp/pip-build-tracker-m7ak8htb
  Created temporary directory: /tmp/pip-install-q5ejdcuo
  Created temporary directory: /tmp/pip-ephem-wheel-cache-in621ed4
  Processing $SRC_DIR
    Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-m7ak8htb'
    Created temporary directory: /tmp/pip-modern-metadata-h1jp4uq7
    Preparing metadata (pyproject.toml): started
    Running command Preparing metadata (pyproject.toml)
    running dist_info
    creating /tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info
    writing /tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/entry_points.txt
    writing requirements to /tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/requires.txt
    writing top-level names to /tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-modern-metadata-h1jp4uq7/rpbp.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-h1jp4uq7/rpbp-3.0.2.dist-info'
    Preparing metadata (pyproject.toml): finished with status 'done'
    Source in $SRC_DIR has version 3.0.2, which satisfies requirement rpbp==3.0.2 from file://$SRC_DIR
    Removed rpbp==3.0.2 from file://$SRC_DIR from build tracker '/tmp/pip-build-tracker-m7ak8htb'
  INFO: pip is looking at multiple versions of rpbp to determine which version is compatible with other requirements. This could take a while.
  Will try a different candidate, due to conflict:
      rpbp 3.0.2 depends on Python <3.11,>=3.7
  [31mERROR: Package 'rpbp' requires a different Python: 3.11.9 not in '<3.11,>=3.7'[0m[31m
  [0mException information:
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
      result = self._result = resolver.resolve(
                              ^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 439, in resolve
      raise ResolutionImpossible(self.state.backtrack_causes)
  pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=RequiresPythonRequirement('<3.11,>=3.7'), parent=LinkCandidate('file://$SRC_DIR'))]

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
      status = run_func(*args)
               ^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
      return func(self, options, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
      requirement_set = resolver.resolve(
                        ^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
      raise error from e
  pip._internal.exceptions.UnsupportedPythonVersion: Package 'rpbp' requires a different Python: 3.11.9 not in '<3.11,>=3.7'
  Removed build tracker: '/tmp/pip-build-tracker-m7ak8htb'
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/rpbp_1718029829416/work/conda_build.sh']' returned non-zero exit status 1.
# Last 100 lines of the build log.
