recipe_sha: eaf28acf9112424b486965c93df8e24c4897dc9cccb231747062fc41bd15ae7b  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  2024-06-04T21:53:41 linux-aarch64 Building current_repodata subset
  2024-06-04T21:53:41 linux-aarch64 Writing current_repodata subset
  2024-06-04T21:53:41 linux-aarch64 Writing index HTML
  2024-06-04T21:53:41 Subdir: noarch Gathering repodata
  2024-06-04T21:53:41 noarch Writing pre-patch repodata
  2024-06-04T21:53:41 noarch Applying patch instructions
  2024-06-04T21:53:41 noarch Writing patched repodata
  2024-06-04T21:53:41 noarch Building current_repodata subset
  2024-06-04T21:53:41 noarch Writing current_repodata subset
  2024-06-04T21:53:41 noarch Writing index HTML
  /opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py:501: UserWarning: RECIPE_PATH received is a file (/opt/recipe/meta.yaml).
  It should be a path to a folder.
  Forcing conda-build to use the recipe file.
    warnings.warn(
  WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
  Adding in variants from internal_defaults
  Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
  Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
  Attempting to finalize metadata for pbcopper
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Getting pinned dependencies: ...working... done
  BUILD START: ['pbcopper-2.3.0-h4ac6f70_1.tar.bz2']
  Reloading output folder (file:///opt/host-conda-bld): ...working... done
  Solving environment (_h_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/pbcopper_1717538022603/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:         0.1-conda_forge            conda-forge
      _openmp_mutex:         4.5-2_gnu                  conda-forge
      boost:                 1.85.0-h9cebb41_1          conda-forge
      bzip2:                 1.0.8-hd590300_5           conda-forge
      ca-certificates:       2024.6.2-hbcca054_0        conda-forge
      icu:                   73.2-h59595ed_0            conda-forge
      ld_impl_linux-64:      2.40-hf3520f5_2            conda-forge
      libblas:               3.9.0-22_linux64_openblas  conda-forge
      libboost:              1.85.0-hba137d9_1          conda-forge
      libboost-devel:        1.85.0-h00ab1b0_1          conda-forge
      libboost-headers:      1.85.0-ha770c72_1          conda-forge
      libboost-python:       1.85.0-py312h389efb2_1     conda-forge
      libboost-python-devel: 1.85.0-py312h9cebb41_1     conda-forge
      libcblas:              3.9.0-22_linux64_openblas  conda-forge
      libexpat:              2.6.2-h59595ed_0           conda-forge
      libffi:                3.4.2-h7f98852_5           conda-forge
      libgcc-ng:             13.2.0-h77fa898_7          conda-forge
      libgfortran-ng:        13.2.0-h69a702a_7          conda-forge
      libgfortran5:          13.2.0-hca663fb_7          conda-forge
      libgomp:               13.2.0-h77fa898_7          conda-forge
      liblapack:             3.9.0-22_linux64_openblas  conda-forge
      libnsl:                2.0.1-hd590300_0           conda-forge
      libopenblas:           0.3.27-pthreads_h413a1c8_0 conda-forge
      libsqlite:             3.45.3-h2797004_0          conda-forge
      libstdcxx-ng:          13.2.0-hc0a3c3a_7          conda-forge
      libuuid:               2.38.1-h0b41bf4_0          conda-forge
      libxcrypt:             4.4.36-hd590300_1          conda-forge
      libzlib:               1.3.1-h4ab18f5_1           conda-forge
      ncurses:               6.5-h59595ed_0             conda-forge
      numpy:                 1.26.4-py312heda63a1_0     conda-forge
      openssl:               3.3.0-h4ab18f5_3           conda-forge
      pip:                   24.0-pyhd8ed1ab_0          conda-forge
      python:                3.12.3-hab00c5b_0_cpython  conda-forge
      python_abi:            3.12-4_cp312               conda-forge
      readline:              8.2-h8228510_1             conda-forge
      setuptools:            70.0.0-pyhd8ed1ab_0        conda-forge
      tk:                    8.6.13-noxft_h4845f30_101  conda-forge
      tzdata:                2024a-h0c530f3_0           conda-forge
      wheel:                 0.43.0-pyhd8ed1ab_1        conda-forge
      xz:                    5.2.6-h166bdaf_0           conda-forge
      zstd:                  1.5.6-ha6fb4c9_0           conda-forge

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2409, in build
      create_build_envs(top_level_pkg, notest)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2183, in create_build_envs
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1332, in _execute_actions
      progressive_fetch_extract.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Error with archive /opt/conda/pkgs/libboost-headers-1.85.0-ha770c72_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
# Last 100 lines of the build log.
