recipe_sha: 36604d19b76e15c04754efeacc0f47dd17d1b98517ae0f8cd032fd567a726fd8  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  bin/mark_prophage_features.py (text): Patching
  bin/phispy (text): Patching
  bin/plot_stats.py (text): Patching
  TEST START: /opt/conda/conda-bld/linux-64/phispy-4.2.21-py38h2123bcc_4.tar.bz2
  Renaming work directory '/opt/conda/conda-bld/phispy_1717714152595/work' to '/opt/conda/conda-bld/phispy_1717714152595/work_moved_phispy-4.2.21-py38h2123bcc_4_linux-64'
  shutil.move(work)=/opt/conda/conda-bld/phispy_1717714152595/work, dest=/opt/conda/conda-bld/phispy_1717714152595/work_moved_phispy-4.2.21-py38h2123bcc_4_linux-64)
  Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/phispy_1717714152595/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:      0.1-conda_forge            conda-forge
      _openmp_mutex:      4.5-2_gnu                  conda-forge
      bcbio-gff:          0.7.1-pyh7cba7a3_1         bioconda
      biopython:          1.81-py38h01eb140_1        conda-forge
      brotli-python:      1.1.0-py38h17151c0_1       conda-forge
      bx-python:          0.11.0-py38h737be40_2      bioconda
      bzip2:              1.0.8-hd590300_5           conda-forge
      ca-certificates:    2024.6.2-hbcca054_0        conda-forge
      certifi:            2024.2.2-pyhd8ed1ab_0      conda-forge
      charset-normalizer: 3.3.2-pyhd8ed1ab_0         conda-forge
      hmmer:              3.4-hdbdd923_1             bioconda
      idna:               3.7-pyhd8ed1ab_0           conda-forge
      joblib:             1.4.2-pyhd8ed1ab_0         conda-forge
      ld_impl_linux-64:   2.40-hf3520f5_2            conda-forge
      libblas:            3.9.0-20_linux64_openblas  conda-forge
      libcblas:           3.9.0-20_linux64_openblas  conda-forge
      libffi:             3.4.2-h7f98852_5           conda-forge
      libgcc-ng:          13.2.0-h77fa898_7          conda-forge
      libgfortran-ng:     13.2.0-h69a702a_7          conda-forge
      libgfortran5:       13.2.0-hca663fb_7          conda-forge
      libgomp:            13.2.0-h77fa898_7          conda-forge
      liblapack:          3.9.0-20_linux64_openblas  conda-forge
      libnsl:             2.0.1-hd590300_0           conda-forge
      libopenblas:        0.3.25-pthreads_h413a1c8_0 conda-forge
      libsqlite:          3.45.3-h2797004_0          conda-forge
      libstdcxx-ng:       13.2.0-hc0a3c3a_7          conda-forge
      libuuid:            2.38.1-h0b41bf4_0          conda-forge
      libxcrypt:          4.4.36-hd590300_1          conda-forge
      libzlib:            1.3.1-h4ab18f5_1           conda-forge
      ncurses:            6.5-h59595ed_0             conda-forge
      numpy:              1.24.4-py38h59b608b_0      conda-forge
      openssl:            3.3.1-h4ab18f5_0           conda-forge
      packaging:          24.0-pyhd8ed1ab_0          conda-forge
      phispy:             4.2.21-py38h2123bcc_4      local
      pip:                24.0-pyhd8ed1ab_0          conda-forge
      platformdirs:       4.2.2-pyhd8ed1ab_0         conda-forge
      pooch:              1.8.1-pyhd8ed1ab_0         conda-forge
      pysocks:            1.7.1-pyha2e5f31_6         conda-forge
      python:             3.8.19-hd12c33a_0_cpython  conda-forge
      python_abi:         3.8-4_cp38                 conda-forge
      readline:           8.2-h8228510_1             conda-forge
      requests:           2.32.3-pyhd8ed1ab_0        conda-forge
      scikit-learn:       1.3.2-py38ha25d942_2       conda-forge
      scipy:              1.10.1-py38h59b608b_3      conda-forge
      setuptools:         70.0.0-pyhd8ed1ab_0        conda-forge
      six:                1.16.0-pyh6c4a22f_0        conda-forge
      threadpoolctl:      3.5.0-pyhc1e730c_0         conda-forge
      tk:                 8.6.13-noxft_h4845f30_101  conda-forge
      urllib3:            2.2.1-pyhd8ed1ab_0         conda-forge
      wheel:              0.43.0-pyhd8ed1ab_1        conda-forge
      xz:                 5.2.6-h166bdaf_0           conda-forge

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3653, in build_tree
      test(pkg, config=metadata.config.copy(), stats=stats)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3397, in test
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1332, in _execute_actions
      progressive_fetch_extract.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Error with archive /opt/conda/pkgs/libopenblas-0.3.25-pthreads_h413a1c8_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/phispy-4.2.21-py38h2123bcc_4.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/biopython-1.81-py38h01eb140_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/scikit-learn-1.3.2-py38ha25d942_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/scipy-1.10.1-py38h59b608b_3.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
# Last 100 lines of the build log.
