recipe_sha: d13c40e2561dd3ae0e0c9525e8725dfcba2bc197aa5ce06a4298b0d59acd0c7c  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/expansionhunter_1717714150130/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:         0.1-conda_forge            conda-forge
      _openmp_mutex:         4.5-2_gnu                  conda-forge
      abseil-cpp:            20210324.2-h9c3ff4c_0      conda-forge
      boost:                 1.85.0-h9cebb41_1          conda-forge
      bzip2:                 1.0.8-hd590300_5           conda-forge
      c-ares:                1.28.1-hd590300_0          conda-forge
      ca-certificates:       2024.6.2-hbcca054_0        conda-forge
      fmt:                   10.2.1-h00ab1b0_0          conda-forge
      gmock:                 1.14.0-ha770c72_1          conda-forge
      gtest:                 1.14.0-h00ab1b0_1          conda-forge
      htslib:                1.20-h5efdd21_1            bioconda
      icu:                   73.2-h59595ed_0            conda-forge
      keyutils:              1.6.1-h166bdaf_0           conda-forge
      krb5:                  1.21.2-h659d440_0          conda-forge
      ld_impl_linux-64:      2.40-hf3520f5_2            conda-forge
      libblas:               3.9.0-22_linux64_openblas  conda-forge
      libboost:              1.85.0-hba137d9_1          conda-forge
      libboost-devel:        1.85.0-h00ab1b0_1          conda-forge
      libboost-headers:      1.85.0-ha770c72_1          conda-forge
      libboost-python:       1.85.0-py312h389efb2_1     conda-forge
      libboost-python-devel: 1.85.0-py312h9cebb41_1     conda-forge
      libcblas:              3.9.0-22_linux64_openblas  conda-forge
      libcurl:               8.8.0-hca28451_0           conda-forge
      libdeflate:            1.20-hd590300_0            conda-forge
      libedit:               3.1.20191231-he28a2e2_2    conda-forge
      libev:                 4.33-hd590300_2            conda-forge
      libexpat:              2.6.2-h59595ed_0           conda-forge
      libffi:                3.4.2-h7f98852_5           conda-forge
      libgcc-ng:             13.2.0-h77fa898_7          conda-forge
      libgfortran-ng:        13.2.0-h69a702a_7          conda-forge
      libgfortran5:          13.2.0-hca663fb_7          conda-forge
      libgomp:               13.2.0-h77fa898_7          conda-forge
      liblapack:             3.9.0-22_linux64_openblas  conda-forge
      libnghttp2:            1.58.0-h47da74e_1          conda-forge
      libnsl:                2.0.1-hd590300_0           conda-forge
      libopenblas:           0.3.27-pthreads_h413a1c8_0 conda-forge
      libsqlite:             3.45.3-h2797004_0          conda-forge
      libssh2:               1.11.0-h0841786_0          conda-forge
      libstdcxx-ng:          13.2.0-hc0a3c3a_7          conda-forge
      libuuid:               2.38.1-h0b41bf4_0          conda-forge
      libxcrypt:             4.4.36-hd590300_1          conda-forge
      libzlib:               1.2.13-h4ab18f5_6          conda-forge
      ncurses:               6.5-h59595ed_0             conda-forge
      numpy:                 1.26.4-py312heda63a1_0     conda-forge
      openssl:               3.3.1-h4ab18f5_0           conda-forge
      pip:                   24.0-pyhd8ed1ab_0          conda-forge
      python:                3.12.3-hab00c5b_0_cpython  conda-forge
      python_abi:            3.12-4_cp312               conda-forge
      readline:              8.2-h8228510_1             conda-forge
      setuptools:            70.0.0-pyhd8ed1ab_0        conda-forge
      spdlog:                1.13.0-hd2e6256_0          conda-forge
      tk:                    8.6.13-noxft_h4845f30_101  conda-forge
      tzdata:                2024a-h0c530f3_0           conda-forge
      wheel:                 0.43.0-pyhd8ed1ab_1        conda-forge
      xz:                    5.2.6-h166bdaf_0           conda-forge
      zlib:                  1.2.13-h4ab18f5_6          conda-forge
      zstd:                  1.5.6-ha6fb4c9_0           conda-forge

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2409, in build
      create_build_envs(top_level_pkg, notest)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2183, in create_build_envs
      environ.create_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1049, in create_env
      _execute_actions(prefix, precs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1332, in _execute_actions
      progressive_fetch_extract.execute()
    File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 891, in execute
      raise CondaMultiError(not_cancelled)
  conda.CondaMultiError: Failed to write to /opt/conda/pkgs/_openmp_mutex-4.5-2_gnu.tar.bz2.partial
    errno: 28
  Failed to write to /opt/conda/pkgs/_openmp_mutex-4.5-2_gnu.tar.bz2.partial
    errno: 28
  Error with archive /opt/conda/pkgs/libboost-devel-1.85.0-h00ab1b0_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Error with archive /opt/conda/pkgs/libboost-python-1.85.0-py312h389efb2_1.conda.  You probably need to delete and re-download or re-create this file.  Message was:

  failed with error: [Errno 28] No space left on device
  Failed to write to /opt/conda/pkgs/python-3.12.3-hab00c5b_0_cpython.conda.partial
    errno: 28
  [Errno 28] No space left on device
  Failed to write to /opt/conda/pkgs/numpy-1.26.4-py312heda63a1_0.conda.partial
    errno: 28
# Last 100 lines of the build log.
